### ISSUE TITLE
Fluorescent dye quantification analysis

### ISSUE THREAD

**Issue by aixnr** [slim-curve/slim-curve#24]
Hello there,

I have a question regarding the SLIM plugin. I have LIF (Leica Image File, generated by Leica LAS confocal application suite). I want to do dye quantification analysis, but the SLIM plugin only accepts lifetime datafile. How do I proceed from LIF to data quantification with SLIM?

If this is not possible with SLIM, what tool should I use for this purpose? Thanks!

**Comment by ctrueden** [comment]
@aksagar Thoughts?

**Comment by aksagar** [comment]
I am not familiar with this image format. @ctrueden, there is way to open LIF file with bio format importer. https://goo.gl/N6llRM, I am not sure if there is any plugin to do quantification after importing.

**Comment by ctrueden** [comment]
@aksagar I think the point is that right now, the SLIM Curve plugin does its own file I/O using Bio-Formats, looking for a lifetime dimension. And if no lifetime dimension is found, it rejects the dataset.

@aixnr What are you hoping to achieve with the SLIM Curve plugin when using a dataset that has no time-resolved lifetime dimension? How do you think SLIM Curve would help your analysis?

**Comment by aixnr** [comment]
Thanks for the reply @ctrueden and @aksagar,

I was mistaken at first when I found this plugin, thought that it would be able to run quantification analysis of the fluorescent emission intensity (based on the keyword "photon counting", I found ]this page on Fiji.sc official website](http://fiji.sc/SLIM_Curve)).

[I've found a strategy to measure the intensity](http://sciencetechblog.com/2011/05/24/measuring-cell-fluorescence-using-imagej/).

**Comment by ctrueden** [comment]
@aixnr Cool, glad you found a workflow that serves your needs!
